project_name: circonus-logwatch

before:
    hooks:
        - go mod tidy
        - ./build_lint.sh

builds:
    -
        main: main.go

        binary: sbin/circonus-logwatchd

        env:
            - CGO_ENABLED=0

        flags: 
            #- -tags dev

        goos:
            - linux
            - freebsd

        goarch:
            - amd64

        ignore:
            -
                goarch: 386

        ldflags: -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.tag={{.Tag}}

archives:
    - 
        id: default
        name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"

        format: tar.gz

        replacements:
            amd64: x86_64

        format_overrides:
            - goos: windows
              format: zip

        files:
            - LICENSE
            - README.md
            - CHANGELOG.md
            - service/*
            - etc/example-circonus-logwatch.yaml
            - etc/log.d/README.md

release:
    github:
        owner: circonus-labs
        name: circonus-logwatch

    prerelease: auto

snapshot:
    name_template: SNAPSHOT-{{.Commit}}

checksum:
    name_template: "{{.ProjectName}}_checksums.txt"
